"""Model-free tests for the generic colpali-rag tool (no 1GB download).

The ColPali model itself is exercised manually; here we lock the plumbing:
config, pdf layer, heatmap geometry/rendering, the store roundtrip (with a fake
embedder), the patch-grid factorization, and the API helpers.
"""

from pathlib import Path

import numpy as np
import pytest
from PIL import Image

from colpali_rag.config import Settings
from colpali_rag.embedder import ColpaliEmbedder
from colpali_rag.heatmap import colorize, normalize, overlay, to_data_uri
from colpali_rag.pdf import Page, extract_page_texts, list_pdfs, render_page_images, text_coverage
from colpali_rag.store import MemoryStore, page_id

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "tests" / "_sample_docs"   # neutral corpus generated by conftest.py


# --- config ---------------------------------------------------------------
def test_settings_env_override(monkeypatch):
    monkeypatch.setenv("COLPALI_MODEL", "vidore/colqwen2-v1.0")
    monkeypatch.setenv("COLPALI_STORE", "qdrant")
    monkeypatch.setenv("COLPALI_PORT", "9001")
    s = Settings.from_env()
    assert s.model == "vidore/colqwen2-v1.0" and s.store == "qdrant" and s.port == 9001


# --- pdf layer ------------------------------------------------------------
def test_pdf_layer():
    pdfs = list_pdfs(DOCS)
    assert pdfs
    imgs = render_page_images(pdfs[0])
    txts = extract_page_texts(pdfs[0])
    assert imgs and imgs[0].mode == "RGB" and len(imgs) == len(txts)
    assert text_coverage(txts) == 1.0
    assert text_coverage(["", " ", ""]) == 0.0


# --- heatmap --------------------------------------------------------------
def test_heatmap_geometry_and_render():
    assert normalize(np.array([[0.0, 5.0], [10.0, 2.0]])).max() == pytest.approx(1.0)
    c = colorize(np.array([0.0, 1.0]))
    assert c.shape == (2, 3) and c.dtype == np.uint8
    page = Image.new("RGB", (120, 200), "white")
    grid = np.random.rand(8, 8)
    ov = overlay(page, grid)
    assert ov.size == page.size and ov.mode == "RGB"     # overlay aligns to page
    assert to_data_uri(ov).startswith("data:image/png;base64,")


# --- patch-grid factorization (geometry) ----------------------------------
def test_grid_shape_matches_aspect():
    assert ColpaliEmbedder._grid_shape(64, (989, 1400)) == (8, 8)     # portrait, square grid
    assert ColpaliEmbedder._grid_shape(12, (1400, 989)) == (4, 3)     # landscape -> wider grid
    nx, ny = ColpaliEmbedder._grid_shape(48, (1000, 500))            # 2:1 landscape
    assert nx * ny == 48 and nx > ny


# --- store roundtrip with a fake embedder ---------------------------------
class _FakeEmbedder:
    model_id = "fake/model"

    def score(self, query, embs):
        return list(embs)  # embs are the scores themselves, for deterministic ranking


def _pages_images():
    recs = [Page("a.pdf", 1, "alpha text"), Page("a.pdf", 2, "beta"), Page("b.pdf", 1, "gamma")]
    imgs = [Image.new("RGB", (30, 40), c) for c in ("red", "green", "blue")]
    return recs, imgs


def test_memory_store_roundtrip(tmp_path):
    recs, imgs = _pages_images()
    store = MemoryStore(_FakeEmbedder(), str(tmp_path)).build_from(recs, imgs, [0.1, 0.9, 0.5])
    assert len(store) == 3
    hits = store.search("q", top_k=2)
    assert [pid for _r, _s, pid in hits] == [page_id("a.pdf", 2), page_id("b.pdf", 1)]  # 0.9, 0.5
    assert store.get_image(page_id("a.pdf", 1)) is not None      # persisted to disk

    reopened = MemoryStore.load(_FakeEmbedder(), str(tmp_path))
    assert len(reopened) == 3
    assert reopened.search("q", top_k=1)[0][2] == page_id("a.pdf", 2)


# --- api snippet helper ---------------------------------------------------
def test_snippet_centers_on_match():
    from colpali_rag.app import _snippet

    text = "intro words " * 20 + "the ETHERNET connector pinout" + " tail" * 20
    snip = _snippet(text, "ethernet connector")
    assert "ETHERNET" in snip and len(snip) < len(text)
    assert _snippet("", "x") == ""
